total_memory_limit = "Infinity"

[[module]]
name = "ls_effector"
load_from = "../../target/wasm32-wasi/release/ls_effector.wasm"
logger_enabled = true

[module.wasi.mapped_dirs]
"/tmp/vault" = "./test_artifacts/temp"
[module.mounted_binaries]
ls = "/bin/ls"
